---
# This role installs apache2

- name: install apache2
  apt: name={{ item }} state=present
  with_items:
      - apache2
      - apache2-utils

- name: start apache2
  service: name=apache2 state=started enabled=yes

- name: change default ports
  template: src=ports.conf.j2 dest=/etc/apache2/ports.conf
  notify: restart apache2

- name: install php5 on apache2
  apt: name={{ item }} state=present
  with_items:
      - libapache2-mod-php5

- name: copy php.ini
  copy: src=php.ini dest=/etc/php5/apache2/php.ini
  notify:
      - restart apache2

