---
# This role installs apache2

- name: install apache2
  apt: name={{ item }} state=present
  with_items:
      - apache2
      - apache2-utils

- name: start apache2
  service: name=apache2 state=started enabled=yes

- name: change default ports
  template: src=ports.conf.j2 dest=/etc/apache2/ports.conf
  notify: restart apache2

