---
# This role will install MySQL and create db user and give permissions.

- name: Install Postgresql package
  apt: name={{ item }} state=present
  with_items:
      - postgresql
      - python-psycopg2

