---
# This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  remote_user: root
  roles:
      - common
      - users
      - ssl
      - firehol
      - fail2ban

# Configure and deploy database servers.
- hosts: mysql
  remote_user: root
  roles:
      - mysql

- hosts: postgresql
  remote_user: root
  roles:
      - postgresql

- hosts: apache2
  remote_user: root
  roles:
      - base-apache

- hosts: nginx
  remote_user: root
  roles:
      - base-nginx
      - deploy-nginx

- hosts: postfix
  remote_user: root
  roles:
      - postfix

- hosts: dovecot
  remote_user: root
  roles:
      - dovecot

# Configure and deploy the web servers. Note that we include two roles here, 
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
#- hosts: webservers
#  remote_user: root
#  roles:
#  - base-apache
#  - web

# Configure and deploy the load balancer(s).
#- hosts: lbservers
#  remote_user: root
#  roles:
#  - haproxy

# Configure and deploy the Nagios monitoring node(s).
#- hosts: monitoring
#  remote_user: root
#  roles:
#      - nagios
