---

- name: create ssl certs directory
  file: path=/etc/ssl/{{DOMAIN}}/certs state=directory mode=0755

- name: create ssl private directory
  file: path=/etc/ssl/{{DOMAIN}}/private state=directory mode=0700

- name: copy ssl certificate
  copy: src=ssl/intermediate/{{DOMAIN}}/certs/root-chain.wildcard.{{DOMAIN}}.cert.pem dest=/etc/ssl/{{DOMAIN}}/certs/root-chain.wildcard.{{DOMAIN}}.cert.pem mode=0644

- name: copy ssl key
  copy: src=ssl/intermediate/{{DOMAIN}}/private/wildcard.{{DOMAIN}}.key.pem dest=/etc/ssl/{{DOMAIN}}/private/wildcard.{{DOMAIN}}.key.pem mode=0600
