---

- name: install firehol
  apt: name=firehol state=present

- name: copy firehol conf
  copy: src=firehol.conf dest=/etc/firehol/firehol.conf

- name: enable firehol
  copy: src=firehol dest=/etc/default/firehol
  notify:
      - restart firehol
