---
# This role installs nginx

- name: Install nginx
  apt: name={{ item }} state=present default_release=jessie-backports
  with_items:
      - nginx

- name: copy h5bp tweaks
  synchronize:
      src: nginx
      dest: /etc
      owner: no
      group: no
      rsync_opts:
          - "--exclude=.git"
          - "--exclude=sites-*"
  notify:
      - restart nginx
