---
- name: install roundcube
  apt: name={{ item }} state=present
  with_items:
      - roundcube
      - roundcube-core
      - roundcube-mysql

#- name: symlink roundcube
#  file: src=/usr/share/roundcube dest=/var/www/html/roundcube state=link

- name: copy roundcube apache2 vhost
  copy: src=roundcube.ordinodacasa.it.apache2 dest=/etc/apache2/sites-available/roundcube.ordinodacasa.it.conf
  notify:
      - reload apache2

- name: symlink roundcube apache2
  file: src=/etc/apache2/sites-available/roundcube.ordinodacasa.it.conf dest=/etc/apache2/sites-enabled/roundcube.ordinodacasa.it.conf state=link
  notify:
      - reload apache2

- name: copy roundcube nginx vhost
  copy: src=roundcube.ordinodacasa.it.nginx dest=/etc/nginx/sites-available/roundcube.ordinodacasa.it
  notify:
      - reload nginx

- name: symlink roundcube nginx
  file: src=/etc/nginx/sites-available/roundcube.ordinodacasa.it dest=/etc/nginx/sites-enabled/roundcube.ordinodacasa.it state=link
  notify:
      - reload nginx

- name: touch sendmail log
  file: path=/var/log/roundcube/sendmail state=touch

- name: touch errors log
  file: path=/var/log/roundcube/errors state=touch
