---

- name: clone repo
  git: repo=git@bitbucket.org:dovps/socketcluster.git version=staging dest=/home/node/git/socketcluster accept_hostkey=yes
  sudo: yes
  sudo_user: node
  notify: deploy socketcluster

- name: setup pm2
  command: pm2 deploy ecosystem.json5 staging setup
  sudo: yes
  sudo_user: node
  notify: deploy socketcluster
  args:
      chdir: /home/node/git/socketcluster
      creates: /home/node/deploy/staging/socketcluster/source
