---
- name: install zabbix
  apt: name={{ item }} state=present
  with_items:
      - zabbix-agent
      - zabbix-server-mysql
      - zabbix-frontend-php

- name: copy zabbix apache2 vhost
  template: src=zabbix.{{DOMAIN}}.apache2.j2 dest=/etc/apache2/sites-available/zabbix.{{DOMAIN}}.conf
  notify:
      - reload apache2

- name: symlink zabbix apache2
  file: src=/etc/apache2/sites-available/zabbix.{{DOMAIN}}.conf dest=/etc/apache2/sites-enabled/zabbix.{{DOMAIN}}.conf state=link
  notify:
      - reload apache2

- name: copy zabbix nginx vhost
  template: src=zabbix.{{DOMAIN}}.nginx.j2 dest=/etc/nginx/sites-available/zabbix.{{DOMAIN}}
  notify:
      - reload nginx

- name: symlink zabbix nginx
  file: src=/etc/nginx/sites-available/zabbix.{{DOMAIN}} dest=/etc/nginx/sites-enabled/zabbix.{{DOMAIN}} state=link
  notify:
      - reload nginx

- name: copy nginx_status
  copy: src=nginx_status dest=/etc/nginx/sites-available/nginx_status
  notify:
      - reload nginx

- name: symlink nginx_status
  file: src=/etc/nginx/sites-available/nginx_status dest=/etc/nginx/sites-enabled/nginx_status state=link
  notify:
      - reload nginx
