---

- name: clone repo
  git: repo=https://github.com/phra/slimerjs-prerender.git version=pm2 dest=/home/node/git/slimerjs-prerender accept_hostkey=yes
  sudo: yes
  sudo_user: node
  notify: deploy prerender

- name: setup pm2
  command: pm2 deploy ecosystem.json5 staging setup
  sudo: yes
  sudo_user: node
  notify: deploy prerender
  args:
      chdir: /home/node/git/slimerjs-prerender
      creates: /home/node/deploy/staging/prerender/source

- name: copy www vhost
  template: src=prerender.{{DOMAIN}}.j2 dest=/etc/nginx/sites-available/prerender.{{DOMAIN}}
  notify: reload nginx

- name: symlink www
  file: src=/etc/nginx/sites-available/prerender.{{DOMAIN}} dest=/etc/nginx/sites-enabled/prerender.{{DOMAIN}} state=link
  notify: reload nginx
