---

- name: install postfix
  apt: name={{ item }} state=present
  with_items:
      - postfix

- name: copy master.cf
  template: src=master.cf.j2 dest=/etc/postfix/master.cf

- name: copy main.cf
  template: src=main.cf.j2 dest=/etc/postfix/main.cf

- name: copy virtual
  template: src=virtual.j2 dest=/etc/postfix/virtual

- name: create virtual.db
  shell: postmap /etc/postfix/virtual
  notify:
      - restart postfix
