---
# This role contains common plays that will run on all nodes.


- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Update system
  apt: upgrade=dist

- name: Install common packages
  apt: name={{ item }} state=present
  with_items:
   - vim
   - vim-runtime
   - build-essential
   - git
   - mercurial
   - mailutils
   - logrotate
   - tmux
   - ansible
   - autoconf
   - automake
   - cmake
   - curl
   - wget
   - mailutils
   - xz-utils
   - exuberant-ctags
   - sudo
   - rsync

