---

- name: deploy prerender
  command: pm2 deploy ecosystem.json5 staging chdir=/home/node/git/slimerjs-prerender
  sudo: yes
  sudo_user: node
  async: 1800
  poll: 120

- name: reload nginx
  service: name=nginx state=reloaded
