---

- name: install piwik
  apt: name={{ item }}
  with_items:
      - piwik

- name: copy piwik apache2 vhost
  copy: src=piwik.ordinodacasa.it.apache2 dest=/etc/apache2/sites-available/piwik.ordinodacasa.it.conf

- name: symlink piwik apache2
  file: src=/etc/apache2/sites-available/piwik.ordinodacasa.it.conf dest=/etc/apache2/sites-enabled/piwik.ordinodacasa.it.conf state=link
  notify:
      - reload apache2

- name: copy piwik nginx vhost
  copy: src=piwik.ordinodacasa.it.nginx dest=/etc/nginx/sites-available/piwik.ordinodacasa.it

- name: symlink piwik nginx
  file: src=/etc/nginx/sites-available/piwik.ordinodacasa.it dest=/etc/nginx/sites-enabled/piwik.ordinodacasa.it state=link
  notify:
      - reload nginx

