---

- name: install piwik
  apt: name={{ item }}
  with_items:
      - piwik

- name: create piwik mysql db
  mysql_db: name={{ piwik_db }}

- name: create piwik mysql user
  mysql_user: name={{ piwik_db_user }} password={{ piwik_db_pass }} priv={{ piwik_db }}.*:ALL

- name: grant FILE permission
  shell: echo "GRANT FILE ON *.* TO 'piwik'@'localhost';" | sudo mysql

- name: set piwik auto-archive crontab
  cron: name=piwik-auto-archive minute=5 user=www-data job="/usr/bin/php5 /usr/share/piwik/console core:archive --url=http://piwik.{{DOMAIN}}"

- name: copy piwik apache2 vhost
  template: src=piwik.{{DOMAIN}}.apache2.j2 dest=/etc/apache2/sites-available/piwik.{{DOMAIN}}.conf

- name: symlink piwik apache2
  file: src=/etc/apache2/sites-available/piwik.{{DOMAIN}}.conf dest=/etc/apache2/sites-enabled/piwik.{{DOMAIN}}.conf state=link
  notify:
      - reload apache2

- name: copy piwik nginx vhost
  template: src=piwik.{{DOMAIN}}.nginx.j2 dest=/etc/nginx/sites-available/piwik.{{DOMAIN}}

- name: symlink piwik nginx
  file: src=/etc/nginx/sites-available/piwik.{{DOMAIN}} dest=/etc/nginx/sites-enabled/piwik.{{DOMAIN}} state=link
  notify:
      - reload nginx
