---

- name: install jenkins
  apt: name={{ item }}
  with_items:
      - jenkins

- name: add jenkins to shadow group
  user: name=jenkins groups=shadow,sudo append=yes

- name: permit jenkins to sudo on node
  copy: src=jenkins dest=/etc/sudoers.d/jenkins
  notify:
      - reload sudo

- name: copy jenkins config
  copy: src=config.xml dest=/var/lib/jenkins/config.xml
  notify:
      - restart jenkins

- name: change default port
  lineinfile: dest=/etc/default/jenkins regexp=^HTTP_PORT= line=HTTP_PORT={{ jenkins_port }}
  notify:
      - restart jenkins

- name: copy jenkins nginx vhost
  template: src=jenkins.ordinodacasa.it.nginx.j2 dest=/etc/nginx/sites-available/jenkins.ordinodacasa.it
  notify:
      - reload nginx

- name: symlink jenkins nginx
  file: src=/etc/nginx/sites-available/jenkins.ordinodacasa.it dest=/etc/nginx/sites-enabled/jenkins.ordinodacasa.it state=link
  notify:
      - reload nginx

